### ISSUE TITLE
How to choose activation function?

### ISSUE THREAD

**Issue by 14H034160212** [nuric/deeplogic#12]
Hi,

I have a question about how to choose the activation function. I see you choose sigmoid and tanh in your program. But I am wondering why you choose these two activation functions? I am experimenting with replacing those activation functions with ReLU, and it does not work better than the sigmoid and tanh. So I am confused about that.
![image](https://user-images.githubusercontent.com/23516191/108135196-92bfd300-711c-11eb-93aa-ac0b8641c736.png)
![image](https://user-images.githubusercontent.com/23516191/108135219-9bb0a480-711c-11eb-83b1-d65168f30d15.png)

**Comment by nuric** [comment]
The `tanh` in the hidden layer of the attention network can be replaced with another activation such as `relu` although as you find out it might not necessarily give better results.

The `sigmoid` is chosen because it fits the domain correctly. In the attention layer, it asks whether a rule is selected or not, 0 or 1 which is the output domain of the sigmoid. Same for gating, use new results or not. And the final predications are binary predictions true or false. So changing sigmoid activation for these cases would result in an incorrect network with undefined behaviour.
