### ISSUE TITLE
Can you share the version of each library you used? 

### ISSUE THREAD

**Issue by 14H034160212** [nuric/deeplogic#2]
Hi, 
Many thanks for the correct version of tensorflow and keras. Can you share the version of each library you used? Especially the version of the matplotlib. I just got the following issue and cannot show the figures. Many thanks.
``/pvol/qbao775/AllanAI/deeplogic-master/eval.py:337: UserWarning: Tight layout not applied. tight_layout cannot make axes width small enough to accommodate all axes decorations plt.tight_layout()``
``/home/qbao775/.pycharm_helpers/pycharm_matplotlib_backend/backend_interagg.py:64: UserWarning: Tight layout not applied. tight_layout cannot make axes width small enough to accommodate all axes decorations self.figure.tight_layout()``

**Comment by nuric** [comment]
Unfortunately, I don't have the frozen version number of matplotlib since it just uses vanilla matplotlib functions. But, that warning seems to be related to the `pycharm` rendering backend. I would recommend commenting out `plt.tight_layout()` in the evaluation script `eval.py`, I believe there are 2 instances. That just changes the layout. If you have the model data, the rest of the plotting is just standard matplotlib.
