### ISSUE TITLE
Some questions about the embedding distribution

### ISSUE THREAD

**Issue by 14H034160212** [nuric/deeplogic#5]
Hi, 
Many thanks for your tips. I have got the embedding diagrams which shows nice distribution. But I have some questions for the meaning of those figures. 

One is for the figure 3. I can get the similar figure by using IMA model. Here is the figure that I got from the IMA model which shows the predicates clustered in vertical columns and constants on horizontal surfaces.
![plot_single_preds_ima](https://user-images.githubusercontent.com/23516191/88131149-66001780-cc30-11ea-8359-8856180f3e58.png)

I also got another figure by using fwimarsm model, but it looks quite different which has a more evident cluster scenario.
![plot_single_preds_fwimarsm](https://user-images.githubusercontent.com/23516191/88131335-d9a22480-cc30-11ea-8cb7-c3e316e1e6be.png)

Here is the initial replication result from the old api and fwimarsm shows the best performance and also the fast training speed.
<img width="465" alt="deeplogic_replication_result" src="https://user-images.githubusercontent.com/23516191/88131460-24bc3780-cc31-11ea-9aac-4c99b262dc45.png">

Here is the figure 5 (a) and figure 5 (b) that I got. I question is from the plot_rule_fwimarsm, it shows ``p(a,b)`` and ``p(a)`` are clustered together. But why they are clustered together? For example, normally we have ``For every X, there exists Y which satisfies p(X,Y) -> p(X)``. So then we can say ``p(a,b)`` and ``p(a)`` are clustered together. What is the theory you used behind the cluster? Or just they looks similar compared with other predicate?

plot_struct_preds_ima
![plot_struct_preds_ima](https://user-images.githubusercontent.com/23516191/88131785-e6734800-cc31-11ea-9c83-1d7289aef61d.png)

![plot_rules_ima](https://user-images.githubusercontent.com/23516191/88131841-09056100-cc32-11ea-88d7-7f5a773a1103.png)

plot_struct_preds_fwimarsm
![plot_struct_preds_fwimarsm](https://user-images.githubusercontent.com/23516191/88131807-f5f29100-cc31-11ea-9a82-62d34d89f00e.png)

plot_rules_fwimarsm
![plot_rules_fwimarsm](https://user-images.githubusercontent.com/23516191/88131869-191d4080-cc32-11ea-9c4c-1af851f02028.png)

**Comment by nuric** [comment]
Thanks for reproducing the results of the paper. It's good to see how the forward chaining model creates clusters as well. Since the forward chaining uses the literal embeddings to learn rule embeddings, we wouldn't expect it to produce the same clustering as the other models directly using the literal embeddings. To answer your other question:

> it shows p(a,b) and p(a) are clustered together. But why they are clustered together?

the models in these tasks tend to learn a clustering based on the structure. So p(a,b) and p(a) are ground atoms, and the clusters are based on, unground atoms, rules with single body condition etc. This is further explained and analysed in the paper under the section analysis.
